services:
  api:
    build: .
    container_name: scam_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: scam_db
    environment:
      POSTGRES_USER: scam_user
      POSTGRES_PASSWORD: scam_pass
      POSTGRES_DB: scam_db
    ports:
      - "5432:5432"
